get http://localhost:5000/notes
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiZGlqYWwiLCJtYWlsIjoiZGlqYWxAZ21haWwuY29tIiwiaWF0IjoxNzQ3MTQ5ODk1LCJleHAiOjE3NDcxNTA3OTV9.PpVEiyx4ecYJn38I4ySP6DNKFjpKANLCLUeNlzVKMK4


###
POST http://localhost:5000/create-notes
Content-Type: application/json

{
    "judul": "Note Pertamaku",
    "isi_catatan": "Lorem ipsum lamor aminor adsaasadsasdads"
}

###
PUT http://localhost:5000/update-notes/13
Content-Type: application/json

{
    "judul": "Note Diubah Pertamaku",
    "isi_catatan": "Aku cinta tcc"
}

###
DELETE http://localhost:5000/delete-notes/6
Content-Type: application/json

###

POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "Kaputra",
    "password": "Kaputra",
    "email": "kaputra@gmail.com"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "kaputra@gmail.com",
    "password": "Kaputra"
}